version: '3'

services:
  rental-prediction:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    restart: unless-stopped
